UMC-MyFit/my-fit-back

src/modules/signUp/signUp.service.js
- 회원가입 기능 수정
- [feature/5-signup #5 ]
<br/>
=> feat(5): 회원가입 기능 수정

package-lock.json, package.json, src/app.js, src/docs/swagger.js, src/modules/signUp/signUp.routes.js
- Swagger 설정
<br/>
<br/>
- [feature/10-swagger #10 ]
<br/>
=> feat(10): Swagger 설정

src/modules/cards/cards.controller.js, src/modules/cards/cards.routes.js, src/modules/cards/cards.service.js, src/routes/index.js
- 이력/활동 카드 등록
- POST /api/cards
🎇로그인 기능 구현 시 코드 수정 필요(session에 담겨있는 service_id를 사용해야 하는데, 임시로 body에 포함해서 수동으로 보내고 있음)
<br/>
<br/>
- [feature/12-post_activity_card #12 ]
<br/>
=> feat(12): 이력/활동 카드 등록

src/modules/cards/cards.controller.js, src/modules/cards/cards.routes.js, src/modules/cards/cards.service.js, src/modules/signUp/signUp.service.js
- 이력/활동 카드 상세 조회 (GET /api/cards/{card_id})
- 회원가입 버그 수정 (POST /api/users)
<br/>
<br/>
- [feature/14-get_detail_activity_card #14 ]
<br/>
=> feat(14)- 이력/활동 카드 상세 조회

src/modules/user/user.controller.js, src/modules/user/user.routes.js, src/modules/user/user.service.js, src/routes/index.js
- 사업자 등록증 등록 기능 구현
- PATCH /api/users/business-license
<br/>
<br/>
- [feature/16-post_business_license #16 ]
<br/>
=> feat(16) - 사업자 등록증 등록 기능 구현

package-lock.json, package.json, src/app.js, src/config/passport.js, src/middlewares/auth.js
- passport.js 설정
<br/>
- [feat/20-passport.js #20 ]
<br/>
=> feat(20): passport.js 설정

src/modules/mypage/mypage.controller.js, src/modules/mypage/mypage.model.js, src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js, src/routes/index.js
- 제목 : feat(29): 마이페이지 - 유저 프로필 조회 기능
- mypage 디렉토리 생성
- 유저 프로필 조회 기능 구현
=> 29 mypage view user

package-lock.json, package.json, src/libs/redisClient.js, src/modules/login/login.routes.js, src/modules/signUp/signUp.routes.js, src/modules/signUp/signUp.service.js, src/modules/user/user.controller.js, src/modules/user/user.routes.js, src/modules/user/user.service.js, src/server.js
- 비밀번호 재설정 API 구현
- PATCH /api/users/password-reset
<br/>
<br/>
- [feature/41-reset_password #41 ]
<br/>
=> feat(41): 비밀번호 재설정

src/modules/signUp/signUp.routes.js, src/modules/signUp/signUp.service.js, src/modules/user/user.controller.js, src/modules/user/user.routes.js, src/modules/user/user.service.js, src/server.js
- 이메일 인증코드 검증 API 구현
- Redis를 항상 연결하는 방식에서 필요할 때만 연결하는 방식으로 수정
<br/>
<br/>
- [feature/43-verify_code #43 ]
<br/>
=> feat(43): 이메일 인증코드 검증

prisma/migrations/20250718130446_add_unique_interest_network_pair_constriant/migration.sql, prisma/schema.prisma, src/modules/mypage/mypage.controller.js, src/modules/mypage/mypage.model.js, src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js
- 제목 : feat(47): 관심 신청/해제
- api/mypage/{target_service_id}/interests
<br/>
<br/>
- [feature/47-interest-setting #47 ]
<br/>
=> feat(47) 관심 신청/해제

src/config/passport.js, src/modules/signUp/signUp.routes.js, src/modules/signUp/signUp.service.js
- UserArea 테이블 변경에 대한 회원가입 로직 수정
<br/>
<br/>
- [bug/60-signUp #60 ]
<br/>
=> bug(60): 회원가입 로직 수정

src/libs/dataTransformer.js, src/modules/recruitments/recruitments.controller.js, src/modules/recruitments/recruitments.routes.js, src/modules/recruitments/recruitments.service.js, src/modules/recruitments/subscription/subscription.controller.js, src/modules/recruitments/subscription/subscription.model.js, src/modules/recruitments/subscription/subscription.service.js
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
- 작업 내용 1
- 작업 내용 2
<br/>
<br/>
<br/>
=> 54 feature cicd 파이프라인 구축

package-lock.json, package.json, src/modules/chatting/chatting.controller.js, src/modules/chatting/chatting.model.js, src/modules/chatting/chatting.routes.js, src/modules/chatting/chatting.service.js, src/modules/user/user.routes.js, src/routes/index.js, src/server.js, src/socket/socket.js
- 채팅방 존재 확인, 메시지 전송, 메시지 조회 API 구현
<br/>
<br/>
- [feature/46-get_message,post_message #46 ]
<br/>
=> Feature(46): 채팅방 존재 확인, 메시지 전송, 메시지 조회

prisma/migrations/20250724090342_add_team_fields/migration.sql, prisma/schema.prisma, src/config/passport.js, src/modules/cards/cards.controller.js, src/modules/cards/cards.routes.js, src/modules/cards/cards.service.js, src/modules/login/login.controller.js, src/modules/login/login.model.js, src/modules/login/login.routes.js, src/modules/signUp/signUp.controller.js, src/modules/signUp/signUp.routes.js, src/modules/signUp/signUp.service.js, src/modules/user/user.service.js
- 팀 회원가입 API 구현
- /api/users/team
- 회원가입 이후 첫 이력/활동 카드 등록 시 자동 로그인 되도록 로직 수정
- 로그인 시 세션에 service_id가 아니라 user_id를 저장하고 있던 버그 수정
<br/>
<br/>
- [feature/70-signUp_team #70 ]
<br/>
=> feat(70): 팀 회원가입

src/modules/cards/cards.service.js, src/modules/feed/feed.model.js, src/modules/mypage/mypage.controller.js, src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js, src/modules/relationships/relationships.controller.js, src/modules/relationships/relationships.routes.js, src/modules/relationships/relationships.service.js
- 마이페이지에서 사용자가 작성한 피드와 활동 카드 조회하는 기능 구현
- /api/mypage/{service_id}/feeds
- /api/mypage/{service_id}/cards
- 마이페이지 설정 기능 구현을 위해 mypage 디렉토리 안에 setting 디렉토리 추가
<br/>
<br/>
- [feature/74-mypage-feeds #74 ]
<br/>
=> feat(74): 마이페이지 피드/활동 카드 조회

src/modules/coffeechat/coffeechat.routes.js, src/modules/coffeechat/coffeechat.service.js
- 커피챗 목록 조회 수정
<br/>
<br/>
- [feature/78-coffeechat_accept #78 ]
<br/>
=> feat(78): 커피챗 목록 조회 수정

prisma/migrations/20250729140524_add_index_to_coffeechat/migration.sql, prisma/schema.prisma
- 메시지 테이블 인덱스 추가
- 커피챗 테이블 인덱스 추가
- [bug/83-add_index_message_table #83 ]
<br/>
=> bug(83):메시지 테이블 및 커피챗 테이블 인덱스 추가

src/modules/mypage/mypage.controller.js, src/modules/mypage/mypage.model.js, src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js, src/modules/mypage/setting/setting.controller.js, src/modules/mypage/setting/setting.model.js, src/modules/mypage/setting/setting.routes.js, src/modules/mypage/setting/setting.service.js, src/routes/index.js
- GET /api/settings/profile api 구현
- PATCH /api/settings/profile api 구현
- 마이페이지 일부 api 오류 수정
<br/>
<br/>
- [feature/81-edit-profile-in-settings #81 ]
<br/>
=> feat(81): 마이페이지 설정 - 유저 프로필 정보 수정

src/modules/coffeechat/coffeechat.controller.js, src/modules/coffeechat/coffeechat.routes.js, src/modules/coffeechat/coffeechat.service.js
- 커피챗 상세 조회 API 구현
<br/>
<br/>
- [feature/102-get_detail_coffeechat #102 ]
<br/>
=> Feature(102): 커피챗 상세 조회

src/modules/mypage/mypage.controller.js, src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js
- 작업 내용 1
- 작업 내용 2
- [레포 이름 #106 ](이슈 주소)
<br/>
=> feat(106): 마이페이지 api 수정

src/modules/mypage/mypage.routes.js, src/modules/mypage/mypage.service.js
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
- 작업 내용 1
- 작업 내용 2
<br/>
<br/>
<br/>
=> /api/mypage/profile_info 에 관심/네트워크 수 추가

prisma/migrations/20250801080913_add_highlight_card/migration.sql, prisma/schema.prisma
- schema.prisma 수정
- [레포 이름 #115 ](이슈 주소)
<br/>
=> feat(115): ActivityCard에 is_highlighted 추가

src/modules/chatting/chatting.controller.js, src/modules/chatting/chatting.routes.js, src/modules/chatting/chatting.service.js
- 채팅방 입장 API 구현
<br/>
<br/>
- [bug/112-little_bit #119 ]
<br/>
=> feat(112): 채팅방 입장 API 구현

src/modules/coffeechat/coffeechat.controller.js, src/modules/coffeechat/coffeechat.routes.js, src/modules/coffeechat/coffeechat.service.js
- 커피챗 요청 req body에서 receiver_id 삭제 및 receiver_id 탐색 로직 추가
- [bug/123-coffeechat_request #123 ]
<br/>
=> feat(123): 커피챗 요청 req body 수정

src/modules/relationships/relationships.controller.js, src/modules/relationships/relationships.model.js, src/modules/relationships/relationships.routes.js, src/modules/relationships/relationships.service.js
- 작업 내용 1
- 작업 내용 2
- [레포 이름 #119]
<br/>
=> feat(119): relationships api 수정

src/modules/coffeechat/coffeechat.service.js
- 커피챗 취소 시 생성되는 메시지에 오타 수정
<br/>
- [bug/127-edit_coffeechat #127 ]
<br/>
=> bug(127): 커피챗 사소한 버그 수정

src/modules/cards/cards.controller.js, src/modules/cards/cards.routes.js, src/modules/cards/cards.service.js
- 이력/활동 카드 직무별 조회 API 구현
<br/>
<br/>
- [bug/129-activitiy_cards #129 ]
<br/>
=> bug(129): 이력/활동 카드 직무별 조회 API 구현

src/modules/cards/cards.controller.js, src/modules/cards/cards.routes.js, src/modules/cards/cards.service.js, src/modules/coffeechat/coffeechat.service.js
- 이력/활동 카드 필터링 개수 조회 API 구현
- 짜잘한 버그 수정
<br/>
<br/>
- [bug/129-activity_cards #129 ]
<br/>
=> Bug(129): 이력/활동 카드 필터링 개수 조회

src/modules/chatting/chatting.controller.js, src/modules/chatting/chatting.model.js, src/modules/chatting/chatting.routes.js, src/modules/chatting/chatting.service.js, src/modules/coffeechat/coffeechat.service.js, src/socket/socket.js
- 채팅 짜잘한 버그들 수정
<br/>
- [bug/133-chatting #133 ]
<br/>
=> bug(133): 채팅 짜잘한 버그들 수정

src/modules/chatting/chatting.routes.js, src/modules/chatting/chatting.service.js
- team 회원일 경우 나이가 안뜨게 수정
- last_message에서 이름이 안나오던 버그 수정
- [bug/138-chatting_room_list #138 ]
<br/>
=> Bug(138): 채팅방 목록 조회 수정

prisma/migrations/20250811091253_add_notification/migration.sql, prisma/schema.prisma, src/modules/feed/feedComments.service.js, src/modules/feed/feedHearts.service.js, src/modules/notification/notification.controller.js, src/modules/notification/notification.routes.js, src/modules/notification/notification.service.js, src/modules/relationships/relationships.model.js, src/modules/relationships/relationships.service.js, src/routes/index.js, src/server.js, src/socket/socket.js
- 댓글 작성, 좋아요 등록, 네트워크 신청, 관심 등록 시 알림 생성
- 알림 테이블 생성
- 알림 목록 조회 API(GET /api/notifications) 구현
- 미확인 알림 존재 여부 조회 API (GET /api/notifications/unread) 구현
- 알림 전체 읽음 처리 API (PATCH /api/notifications/read-all) 구현
<br/>
<br/>
- [feature/144-alarm #144 ]
<br/>
=> feat(144): 알림 기능 구현

src/modules/chatting/chatting.service.js, src/modules/coffeechat/coffeechat.routes.js, src/modules/coffeechat/coffeechat.service.js
- 최근 메시지를 보낸 채팅방 기준으로 정렬하도록 수정
- 예정된 커피챗 조회 시 division도 응답하도록 수정
- 지난 커피챗 조회 시 division도 응답하도록 수정
- [bug/149-chatting_list #149 ]
<br/>
=> bug/149-채팅방 목록 조회 로직 수정

prisma/migrations/20250813090707_widen_password_len/migration.sql, prisma/schema.prisma, src/modules/login/login.service.js, src/modules/signUp/signUp.service.js, src/modules/user/user.controller.js, src/modules/user/user.routes.js, src/modules/user/user.service.js
- 비밀번호 암호화 작업
- 유저 유효성 확인 res body에 authCode 추가
- 기업 회원 사업자 등록증 버그 수정
<br/>
- [bug/156-check_email_password #156 ]
<br/>
=> bug/156: 비밀번호 암호화 작업 및 유저 유효성 확인 버그 수정

prisma/migrations/20250813112643_image_url_size_up/migration.sql, prisma/schema.prisma
- 스키마에서 이미지는 VarChar(500)으로 통일
- [bug/158-schema #158 ]
<br/>
=> bug/158- 스키마 이미지 글자수 수정

src/modules/user/user.controller.js, src/modules/user/user.routes.js, src/modules/user/user.service.js
- 회원 탈퇴 API 구현
<br/>
<br/>
- [feature/160-delete_user #160 ]
<br/>
=> feature/160- 회원 탈퇴 API 구현

src/modules/signUp/signUp.service.js
- 비밀번호 암호화 과정 오류 수정
-[bug/162-signUp #162 ]
<br/>
=> bug/162-회원가입 핫픽스
